### ISSUE TITLE
[nexus-repository-manager] with nexus.properties.override=true logback folder is missing

### ISSUE THREAD

**Issue by EugenMayer** [sonatype/helm3-charts#137]
When using `nexus.properties.override = true` the start fails with an exception since logback folder cannot be accessed (since it is missing). 

Currently, if fix this using an initContainer

```yaml
    - name: fix-nexus-data-logback
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args:
        - -c
        # mkdir -p is need to fix an exception on boot that the folder is missing if nexus.properties.override = true is set
        - >
          mkdir -p /nexus-data/etc/logback;
      volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
```
