### ISSUE TITLE
Error at deploy if add two registries with same port

### ISSUE THREAD

**Issue by F43RY** [sonatype/helm3-charts#158]
Hi,
I have the following error when deploy the chart containing 2 different registries with same port:

`Error: services "nexus3-nexus-repository-manager-docker-5000" already exists`

The following is a part of my values.yaml in nexus.docker.registries configuration: 

```
nexus:
  docker:
    enabled: true
    registries:
      - host: registry.fe.mydomain.local
        port: 5000
        secretName: secret-nexus
      - host: registry.be.mydomain.local
        port: 5000
        secretName: secret-nexus
```

I think the generated name of service in template should not be based only on port number but on further details.
AFAIU the problem could be the following line (38)  in service.yaml template where service name is generated:

`name: {{ include "nexus.fullname" $ | trunc 49 }}-docker-{{ $registry.port }}`

thx
