### ISSUE TITLE
ingressClassName support for registry

### ISSUE THREAD

**Issue by gmcmullankx** [sonatype/helm3-charts#166]
After upgrading to Chart 37.3.2 and updating values to use ingressClassName rather than annotation, the docker registry is not accessible.

Should ingressClassName support be added to https://github.com/sonatype/helm3-charts/blob/main/charts/nexus-repository-manager/templates/ingress.yaml#L49-L79 also?

To resolve this I applied the change to the docker ingress.

```
spec:
  ingressClassName: nginx
  rules:
  - host: registry.foo.bar.com
    http:
      paths:
      - backend:
          service:
            name: nexus3-nexus-repository-manager-docker-5000
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - registry.foo.bar.com
    secretName: registry-tls-secret
```

**Comment by sjentzsch** [comment]
Ugly workaround:
```
[...]
      ingress:
        # until https://github.com/sonatype/helm3-charts/issues/166 is resolved (resp. https://github.com/sonatype/helm3-charts/pull/163 merged), we will stick to annotations, which affects all ingresses
        ingressClassName: false
        annotations:
          kubernetes.io/ingress.class: myIngressClass
```
