### ISSUE TITLE
How to create docker registries that expose ports?

### ISSUE THREAD

**Issue by SomniVertix** [sonatype/helm3-charts#202]
Looking at using the helm3 chart for Nexus and ran into an issue. When trying to create a docker repository, it requires that you provide a port. For security reasons, we want to have multiple docker repositories which would mean multiple ports. And since this is in a helm chart, there doesn't seem to be a way to tell it to open up those ports through the chart. Am I possibly missing something?

**Comment by tculp** [comment]
In the values file, it shows
```
nexus:
  docker:
    enabled: false
    # registries:
    #   - host: chart.local
    #     port: 5000
    #     secretName: registry-secret
```
which is used by the service and ingress templates to expose ports for the docker registries.
