### ISSUE TITLE
allow to setup admin password

### ISSUE THREAD

**Issue by mkyc** [sonatype/helm3-charts#208]
Currently I have:

```yaml
nexus:
  properties:
    override: true
    data:
      nexus.security.randompassword: false
```

and it allows me to use automation to connect with nexus rm using `admin/admin123` but that is problematic in some automations (like terraform with in-house provider connecting using those credentials) to change password. 

I think there should be property named `nexus.admin.password` which would setup password to given string. 

I also noticed `secret` section of configuration and I suspect this could be used but I cannot find any documentation if that would solve my problem.
