### ISSUE TITLE
I did restart nexus pod, and now my docker repository url returning 404

### ISSUE THREAD

**Issue by grigoryevandrey** [sonatype/helm3-charts#232]
I needed to restart a pod to resize bound pvc. After i did it, pvc became resized, but docker registry became unavailable (now url returns 404 nginx message). Only thing that i did change was persistence.storageSize value. Nexus is functioning normally, i can work with main url and other registries, but docker registry is seems to be down. DNS and ingress are configured properly.

What could be the reason? I've been stumbling in this issue all day

**Comment by grigoryevandrey** [comment]
I found out that docker registry ingress is not assigning ip address to it
I tried to delete whole chart (except pvcs) and reinstall it, but nothing has changed. Main ingress has ip address assigned to it, and docker registry ingress does not have it.

That is weird because everything worked fine before with same values, i only changed size of the persistent storage

**Comment by grigoryevandrey** [comment]
Okay i figured out what caused this issue.

Somehow, chart did not assign `spec.ingressClassName: 'nginx'`  to docker registry ingress. When i assigned it with `kubectl edit`, it solved the issue. I guess it should be fixed in chart

**Comment by roelofjansen** [comment]
Hi,

Thanks for the hint about the ingress class. That solved the same problem I had (404)! 

I looked in the chart template for ingress and found out that you can set extraLabels and annotations on the docker ingress. They should come after "port".

```
    docker:
      enabled: true
      registries:
        - host: registry-nexus.example.com
          port: 5003
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "2G"
            nginx.org/client-max-body-size: 2G
```

So I used the deprecated kubernetes.io/ingress.class annotation for now.

I think you are right they should support the newer ingressClassName spec.

Regards,
Roelof.

**Comment by roelofjansen** [comment]
Unfortunately the deprecated ingress.class annotation is removed by helm. I fixed it by adding a kustomization.yaml

```
patchesJson6902:
  - path: patch-ingress-docker.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: nexus-repository-manager-docker-5000
      version: v1
```

patch-ingress-docker.yaml:
```
- op: add
  path: "/spec/ingressClassName"
  value: "nginx"
```

But off course the chart should still be fixed!
