### ISSUE TITLE
k8s internal ingress docker repository

### ISSUE THREAD

**Issue by dangelkov-skyfi** [sonatype/helm3-charts#235]
I have multiple (two) nginx ingress controllers running in our k8s cluster in google cloud. One is internal ingress with internal load balancer and the other is external one. for ingress in the chart I have 
```
ingress:
  enabled: true
  ingressClassName: nginx-internal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    # kubernetes.io/ingress.class: nginx-internal
  hostPath: /
  hostRepo: nexus.domain.com
  tls:
    - secretName: secret-name
      hosts:
        - nexus.domain.com
```
So far so good, when I deploy with that ingress settings everything works as expected and I can access the web interface with no problem. 

The problem comes when I enable docker registry like this: 
```
  docker:
    enabled: true
    registries:
      - host: docker.domain.com
        port: 5000
        secretName: secret-name
```
the above creates another ingress but the problem is that I can not specify the ingress class for it and I can not access it. 

I tried to set one of my ingress classes as default but it didn't work. 

My k8s version is 1.22 so I can not use annotations for this I can only use `ingressClass` to specify the desired ingress class to use. 

Could you please help with this or possibly upgrade the chart so I can specify the ingress class in the docker configuration part. 

Thank you in advance for your time
