### ISSUE TITLE
helm templating breaks for imagePullSecrets in helm chart > v41.1.0

### ISSUE THREAD

**Issue by ricardojdsilva87** [sonatype/helm3-charts#239]
Hello everyone,

Was trying to deploy the nexus helm chart latest version (41.1.3) and noticed that the generated deployment.yaml template is breaking when using **imagePullSecrets**.
This is the resulting template:
```yaml
   spec:
      serviceAccountName: nexus-sonatype
      imagePullSecrets:
        Capabilities:
          APIVersions:
          - v1
          - admissionregistration.k8s.io/v1
          - admissionregistration.k8s.io/v1beta1
          - internal.apiserver.k8s.io/v1alpha1
          - apps/v1
          - apps/v1beta1
          - apps/v1beta2
          - authentication.k8s.io/v1
          - authentication.k8s.io/v1beta1
          - authorization.k8s.io/v1
          - authorization.k8s.io/v1beta1
          - autoscaling/v1
          - autoscaling/v2
          - autoscaling/v2beta1
          - autoscaling/v2beta2
          - batch/v1
          - batch/v1beta1
          - certificates.k8s.io/v1
          - certificates.k8s.io/v1beta1
          - coordination.k8s.io/v1beta1
          - coordination.k8s.io/v1
          - discovery.k8s.io/v1
          - discovery.k8s.io/v1beta1
          - events.k8s.io/v1
          - events.k8s.io/v1beta1
          - extensions/v1beta1
          - flowcontrol.apiserver.k8s.io/v1alpha1
          - flowcontrol.apiserver.k8s.io/v1beta1
          - flowcontrol.apiserver.k8s.io/v1beta2
          - networking.k8s.io/v1
          - networking.k8s.io/v1alpha1
          - networking.k8s.io/v1beta1
          - node.k8s.io/v1
          - node.k8s.io/v1alpha1
          - node.k8s.io/v1beta1
          - policy/v1
          - policy/v1beta1
          - rbac.authorization.k8s.io/v1
          - rbac.authorization.k8s.io/v1beta1
          - rbac.authorization.k8s.io/v1alpha1
          - scheduling.k8s.io/v1alpha1
          - scheduling.k8s.io/v1beta1
          - scheduling.k8s.io/v1
          - storage.k8s.io/v1beta1
          - storage.k8s.io/v1
          - storage.k8s.io/v1alpha1
          - apiextensions.k8s.io/v1beta1
          - apiextensions.k8s.io/v1
          HelmVersion:
            git_commit: ce66412a723e4d89555dc67217607c6579ffcb21
            git_tree_state: clean
            go_version: go1.19.1
            version: v3.10.0
          KubeVersion:
            Major: "1"
            Minor: "25"
            Version: v1.25.0
        Chart:
          IsRoot: true
          apiVersion: v2
          appVersion: 3.41.1
          description: Sonatype Nexus Repository Manager - Universal Binary repository
          home: https://www.sonatype.com/nexus-repository-oss
          icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
          keywords:
          - artifacts
          - dependency
          - management
          - ...
```
I've downloaded the chart artifact for v41.1.0 and 41.1.3 and the main difference is the following:
**v41.1.0**
```yaml
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
**v41.1.1-v41.1.3**
```yaml
      {{- if .Values.nexus.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```
The main difference is that the values needs to be inside the nexus spec on the values file. The resulting template when this is done is that it seems that the entire API command for helm is printed into the resulting deployment.yaml file

On the values file this is used:
**v41.1.0**
```yaml
imagePullSecrets:
  - name: pull-image-secret
```
**v41.1.1-v41.1.3**
```yaml
nexus:
  imagePullSecrets:
    - name: pull-image-secret
```

This can be tested with the following command:
```bash
helm --debug template nexus nexus/nexus-repository-manager --values=values.yaml --version v41.1.3
```

I'm not really sure what might be the issue here because the change seems to be pretty straight forward, just moving the values to a new location inside the values file. Already tested various scenarios and can confirma that this issue is happening on the versions > 41.1.0

Thanks for your support
