### ISSUE TITLE
Data and Logs PVCs share the same storageSize 

### ISSUE THREAD

**Issue by fbordallo** [sonatype/helm3-charts#248]

**Comment by ke5C2Fin** [comment]
Why is this still not fixed?
This can be done with a helm post renderer, in this code it was done using flux, but post renderers can be passed in on the command line as well.
```
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: PersistentVolumeClaim
          name: nexus-iq-nexus-iq-server-log
        patch: |
          - op: replace
            path: /spec/resources/requests/storage
            value: 10Gi
```
