### ISSUE TITLE
[Nexus IQ server helm chart] configYaml is not working

### ISSUE THREAD

**Issue by Freydiere** [sonatype/helm3-charts#284]
I might be mistaken, but it seems to me that modifying the configYaml field does not impact the installed chart. For example, here is an extract of my values.yaml file:

```yaml
configYaml:
                baseUrl: http://iq-server.demo
                createSampleData: true
                features:
                  enableUnauthenticatedPages: true
                initialAdminPassword: admin
                licenseFile: /etc/nexus-iq-license/license_lic
                logging:
                  appenders:
                  - logFormat: '%d{''yyyy-MM-dd HH:mm:ss,SSSZ''} %level [%thread] %X{username} %logger
                      - %msg%n'
                    threshold: INFO
                    type: console
                  - archivedFileCount: 50
                    archivedLogFilenamePattern: /var/log/nexus-iq-server/clm-server-%d.log.gz
                    currentLogFilename: /var/log/nexus-iq-server/clm-server.log
                    logFormat: '%d{''yyyy-MM-dd HH:mm:ss,SSSZ''} %level [%thread] %X{username} %logger
                      - %msg%n'
                    threshold: ALL
                    type: file
                  level: DEBUG
                  loggers:
                    com.sonatype.insight.audit:
                      appenders:
                      - archivedFileCount: 50
                        archivedLogFilenamePattern: /var/log/nexus-iq-server/audit-%d.log.gz
                        currentLogFilename: /var/log/nexus-iq-server/audit.log
                        type: file
                    com.sonatype.insight.policy.violation:
                      appenders:
                      - threshold: INFO
                        type: console
                    com.sonatype.insight.scan: INFO
                    eu.medsea.mimeutil.MimeUtil2: INFO
                    org.apache.http: INFO
                    org.apache.http.wire: ERROR
                    org.apache.shiro.web.filter.authc.BasicHttpAuthenticationFilter: INFO
                    org.eclipse.birt.report.engine.layout.pdf.font.FontConfigReader: WARN
                    org.eclipse.jetty: INFO
                server:
                  adminConnectors:
                  - port: 8071
                    type: http
                  applicationConnectors:
                  - port: 8070
                    type: http
                  requestLog:
                    appenders:
                    - archivedFileCount: 50
                      archivedLogFilenamePattern: /var/log/nexus-iq-server/request-%d.log.gz
                      currentLogFilename: /var/log/nexus-iq-server/request.log
                      logFormat: '%clientHost %l %user [%date] "%requestURL" %statusCode %bytesSent
                        %elapsedTime "%header{User-Agent}"'
                      type: file
                sonatypeWork: /sonatype-work
```

This is the default config.yml file, except for the initialAdminPassword: here, the password is "admin" and not "admin123", yet after IQ is installed, I can't login with the credentials admin/admin, but the credentials admin/admin123 work. 

It is interesting to note that the file /etc/nexus-iq-server/config.yml in the pod is indeed the one I provided (with the password "admin").

If I did something wrong, please explain me how I should proceed. Otherwise, it would be great if you could fix this issue.
