### ISSUE TITLE
Support to block /swagger-ui

### ISSUE THREAD

**Issue by alexandrud** [sonatype/helm3-charts#83]
Hi,

This is basically a feature request. It would be nice to have support in the ingress template to block /swagger-ui. Other people have asked for it: https://community.sonatype.com/t/is-it-possible-to-protect-or-disable-the-swagger-ui/6077

For AWS load balancer controller a flag in values file to block swagger-ui can trigger a conditional block that will add an additional rule:
```
- host: {{ .Values.ingress.hostRepo }}
    http:
      paths:
      - backend:
          serviceName: response-404
          servicePort: use-annotation
        path: /swagger-ui*
```
And the annotation to the ingress:
```
alb.ingress.kubernetes.io/actions.response-404: >
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"404","MessageBody":"404 error text"}}
```
